In [3]:
import numpy as np

In [4]:
names = [
  'Syrian Government',
  'Syrian Rebels',
  'ISIS',
  'Jabhat al-Nusra',
  'Kurds',
  'U.S. and Allies',
  'Iraq',
  'Iran and Hezbollar',
  'Russia',
  'Saudi Arabia, Gulf States',
  'Turkey',
];

In [5]:
positive_conns = [
  [1, 7],
  [1, 8],
  [1, 9],
  [2, 6],
  [2, 10],
  [2, 11],
  [5, 6],
  [5, 8],
  [5, 9],
  [6, 7],
  [6, 10],
  [6, 11],
  [7, 8],
  [7, 9],
  [8, 9],
  [10, 11],
];

In [6]:
negative_conns = [
  [1, 2],
  [1, 3],
  [1, 4],
  [1, 6],
  [1, 10],
  [1, 11],
  [2, 3],
  [2, 7],
  [2, 8],
  [2, 9],
  [3, 4],
  [3, 5],
  [3, 6],
  [3, 7],
  [3, 8],
  [3, 9],
  [3, 10],
  [3, 11],
  [4, 5],
  [4, 6],
  [4, 7],
  [4, 8],
  [4, 9],
  [5, 7],
  [5, 11],
  [8, 10],
  [9, 10],
  [9, 11],
];


In [11]:
num_nodes = len(names)
A = np.zeros((num_nodes, num_nodes))

for _ in positive_conns:
    A[_[0]-1, _[1]-1] = 1
    A[_[1]-1, _[0]-1] = 1

for _ in negative_conns:
    A[_[0]-1, _[1]-1] = -1
    A[_[1]-1, _[0]-1] = -1

In [23]:
def count_negatives(A):
    return np.count_nonzero(A[A<0])

In [131]:
s = np.ones((1, num_nodes))
frust_index = num_nodes * num_nodes;
frust_switching = np.zeros((1, num_nodes))
count = 1

In [132]:
def switching(n, s, i):
    global frust_index, frust_switching
    if i >= n:
        iter_frust = count_negatives(s*A*s.T)
        if iter_frust < frust_index:
            frust_index = iter_frust
            print(s, frust_index)
        return
    switching(n, s, i+1)
    s[0, i] = -1
    switching(n, s, i+1)

In [133]:
switching(num_nodes, s, 0)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 56
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1.]] 54
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1. -1. -1.]] 48
[[ 1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1.]] 46
[[ 1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1.]] 38
[[ 1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1.]] 32


In [135]:
frust_switching = np.array([[ 1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1,]])

In [70]:
s

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [138]:
switching = frust_switching*A*frust_switching.T

In [142]:
switching+A

array([[ 0., -2., -2., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-2.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-2., -2.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-2.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  2., -2.,  2.,  2.,  0., -2.],
       [ 0.,  0.,  0.,  0.,  2.,  0.,  2.,  0.,  0.,  2.,  2.],
       [ 0.,  0.,  0.,  0., -2.,  2.,  0.,  2.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.,  0.,  2.,  0.,  2., -2.,  0.],
       [ 0.,  0.,  0.,  0.,  2.,  0.,  2.,  2.,  0., -2., -2.],
       [ 0.,  0.,  0.,  0.,  0.,  2.,  0., -2., -2.,  0.,  2.],
       [ 0.,  0.,  0.,  0., -2.,  2.,  0.,  0., -2.,  2.,  0.]])

In [140]:
A

array([[ 0., -1., -1., -1.,  0., -1.,  1.,  1.,  1., -1., -1.],
       [-1.,  0., -1.,  0.,  0.,  1., -1., -1., -1.,  1.,  1.],
       [-1., -1.,  0., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1.,  0., -1.,  0., -1., -1., -1., -1., -1.,  0.,  0.],
       [ 0.,  0., -1., -1.,  0.,  1., -1.,  1.,  1.,  0., -1.],
       [-1.,  1., -1., -1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.],
       [ 1., -1., -1., -1., -1.,  1.,  0.,  1.,  1.,  0.,  0.],
       [ 1., -1., -1., -1.,  1.,  0.,  1.,  0.,  1., -1.,  0.],
       [ 1., -1., -1., -1.,  1.,  0.,  1.,  1.,  0., -1., -1.],
       [-1.,  1., -1.,  0.,  0.,  1.,  0., -1., -1.,  0.,  1.],
       [-1.,  1., -1.,  0., -1.,  1.,  0.,  0., -1.,  1.,  0.]])

In [141]:
switching

array([[ 0., -1., -1., -1., -0.,  1., -1., -1., -1.,  1.,  1.],
       [-1.,  0., -1.,  0., -0., -1.,  1.,  1.,  1., -1., -1.],
       [-1., -1.,  0., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  0., -1.,  0.,  1.,  1.,  1.,  1.,  1., -0., -0.],
       [-0., -0.,  1.,  1.,  0.,  1., -1.,  1.,  1.,  0., -1.],
       [ 1., -1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.],
       [-1.,  1.,  1.,  1., -1.,  1.,  0.,  1.,  1.,  0.,  0.],
       [-1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  1., -1.,  0.],
       [-1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0., -1., -1.],
       [ 1., -1.,  1., -0.,  0.,  1.,  0., -1., -1.,  0.,  1.],
       [ 1., -1.,  1., -0., -1.,  1.,  0.,  0., -1.,  1.,  0.]])